services:
  proof-server:
    image: midnightnetwork/proof-server:3.0.7
    ports:
      - "6300:6300"
    command: "'midnight-proof-server --network testnet'"
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", ":> /dev/tcp/127.0.0.1/6300 || exit 1"]
